CREATE DATABASE image_db;
USE image_db;

CREATE TABLE images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    filepath VARCHAR(255) NOT NULL
);

ALTER TABLE images
ADD detect BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE images
ADD defect BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE images
ADD defect_filename VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE images
ADD defect_filepath VARCHAR(255) NOT NULL DEFAULT '';
